export const THEMES = [
  {
    name: 'Pastel Press',
    tagline: 'Porcelain paper, playful pastels, ink outlines. An editorial zine for your brain.',
    bg: {
      primary: '#f0efea',
      secondary: '#fbfaf7',
      tertiary: '#e6e5dd',
      hover: '#dedcd1',
    },
    border: '#d5d3c6',
    text: {
      primary: '#1b1a16',
      secondary: '#54524a',
      muted: '#8f8d81',
    },
    accents: {
      music: '#a88ff0',
      movies: '#f2799f',
      tv: '#7fadea',
      books: '#8fae4e',
      primary: '#d95f8f',
      hover: '#c14a79',
    },
    nav: {
      bg: '#1b1a16',
      text: '#f5f4ef',
      active: '#f6a8c5',
    },
    gradient: 'linear-gradient(135deg, #f0efea 0%, #ecebe4 50%, #f3f2ed 100%)',
    headingFont: "'Bricolage Grotesque', sans-serif",
    bodyFont: "'Karla', sans-serif",
    vibe: 'Cool porcelain paper, ink outlines, and candy-pastel color blocks. Editorial-zine energy, zero beige-book-app vibes.',
  },
  {
    name: 'Velvet Darkroom',
    tagline: 'The ink zine after dark: deep violet paper and glowing pastel blocks',
    bg: {
      primary: '#131019',
      secondary: '#1c1726',
      tertiary: '#262031',
      hover: '#302a3d',
    },
    border: '#3c3450',
    text: {
      primary: '#f0ecf8',
      secondary: '#aca2c2',
      muted: '#71678c',
    },
    accents: {
      music: '#b9a3f5',
      movies: '#f48bab',
      tv: '#8fb8ef',
      books: '#a9c46a',
      primary: '#ef85ad',
      hover: '#e56b9a',
    },
    nav: {
      bg: '#f0ecf8',
      text: '#1c1726',
      active: '#c14a79',
    },
    gradient: 'linear-gradient(135deg, #131019 0%, #201631 50%, #14101c 100%)',
    headingFont: "'Bricolage Grotesque', sans-serif",
    bodyFont: "'Karla', sans-serif",
    vibe: 'The same editorial-zine ink language on deep violet paper. Pastel blocks glow like neon signs in a cinema lobby after midnight.',
  },
  {
    name: 'Analog Cream',
    tagline: 'The ink zine on warm paper: cream stock and terracotta ink',
    bg: {
      primary: '#f5f0e8',
      secondary: '#fdf9f2',
      tertiary: '#eae4d6',
      hover: '#e0d8c6',
    },
    border: '#d6cdb8',
    text: {
      primary: '#241f19',
      secondary: '#5c5347',
      muted: '#8a7e6f',
    },
    accents: {
      music: '#a180e2',
      movies: '#e57a8d',
      tv: '#6f9fd8',
      books: '#94a851',
      primary: '#d0693a',
      hover: '#b85527',
    },
    nav: {
      bg: '#241f19',
      text: '#f5f0e8',
      active: '#eb9a68',
    },
    gradient: 'linear-gradient(135deg, #f5f0e8 0%, #ebe0d0 50%, #f2ede5 100%)',
    headingFont: "'Bricolage Grotesque', sans-serif",
    bodyFont: "'Karla', sans-serif",
    vibe: 'The editorial-zine look printed on warm cream stock. Terracotta ink and toasted pastels, like a well-loved paperback with sharp outlines.',
  },
  {
    name: 'Neon Noir',
    tagline: 'The ink zine at 2am: true black paper, electric pastels',
    bg: {
      primary: '#08080c',
      secondary: '#101018',
      tertiary: '#181824',
      hover: '#20202e',
    },
    border: '#2a2a40',
    text: {
      primary: '#ecedf5',
      secondary: '#9092b0',
      muted: '#5c5e78',
    },
    accents: {
      music: '#dd8ffa',
      movies: '#ff6b81',
      tv: '#58c4f7',
      books: '#5ce39c',
      primary: '#ff4d9a',
      hover: '#e83384',
    },
    nav: {
      bg: '#ecedf5',
      text: '#101018',
      active: '#e01070',
    },
    gradient: 'linear-gradient(135deg, #08080c 0%, #0d0818 50%, #080a10 100%)',
    headingFont: "'Bricolage Grotesque', sans-serif",
    bodyFont: "'Karla', sans-serif",
    vibe: 'The same ink outlines cut into true black. Electric pastels read like neon through a rain-streaked window. Sharp, modern, unapologetic.',
  },
]

export const DEFAULT_THEME_INDEX = 0

// The current "warm olive" theme as the default CSS fallback
export const WARM_OLIVE = {
  name: 'Warm Olive',
  bg: { primary: '#1c1915', secondary: '#262219', tertiary: '#332e24', hover: '#3d3729' },
  border: '#4a432f',
  text: { primary: '#f0ebe0', secondary: '#b8ad96', muted: '#877e6a' },
  accents: { music: '#c47aff', movies: '#ff6b5a', tv: '#5bb8f5', books: '#7ec87e', primary: '#d4935e', hover: '#c17f48' },
}
